// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwkAvX0VfBnDRIp9UzKOEzVR2ITO2Hc0',
    appId: '1:799616834740:web:2a5a55855b2d7a98bd4be1',
    messagingSenderId: '799616834740',
    projectId: 'groceryapp-efe64',
    authDomain: 'groceryapp-efe64.firebaseapp.com',
    storageBucket: 'groceryapp-efe64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-FDsEhKhSmPNI4Nue7Ko4Y8LlDP95XI',
    appId: '1:799616834740:android:63fee38a42f26871bd4be1',
    messagingSenderId: '799616834740',
    projectId: 'groceryapp-efe64',
    storageBucket: 'groceryapp-efe64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESIC1ySs8rm77_cGQVfCfP-K7pK2ld9U',
    appId: '1:799616834740:ios:9e56f05869880e1bbd4be1',
    messagingSenderId: '799616834740',
    projectId: 'groceryapp-efe64',
    storageBucket: 'groceryapp-efe64.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESIC1ySs8rm77_cGQVfCfP-K7pK2ld9U',
    appId: '1:799616834740:ios:9e56f05869880e1bbd4be1',
    messagingSenderId: '799616834740',
    projectId: 'groceryapp-efe64',
    storageBucket: 'groceryapp-efe64.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbwkAvX0VfBnDRIp9UzKOEzVR2ITO2Hc0',
    appId: '1:799616834740:web:7386606fd5bc88e4bd4be1',
    messagingSenderId: '799616834740',
    projectId: 'groceryapp-efe64',
    authDomain: 'groceryapp-efe64.firebaseapp.com',
    storageBucket: 'groceryapp-efe64.appspot.com',
  );

}